//
// ColumnSpecification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ColumnSpecification: Codable, JSONEncodable, Hashable {

    public var column: String
    public var table: String

    public init(column: String, table: String) {
        self.column = column
        self.table = table
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case column
        case table
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(column, forKey: .column)
        try container.encode(table, forKey: .table)
    }
}

