//
// DistinctElementsResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DistinctElementsResult: Codable, JSONEncodable, Hashable {

    public var queryId: String?
    public var distinctElements: [String]?

    public init(queryId: String? = nil, distinctElements: [String]? = nil) {
        self.queryId = queryId
        self.distinctElements = distinctElements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryId
        case distinctElements
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(queryId, forKey: .queryId)
        try container.encodeIfPresent(distinctElements, forKey: .distinctElements)
    }
}

