//
// ExtractionItemContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExtractionItemContainer: Codable, JSONEncodable, Hashable {

    public var object: MediaObjectDescriptor?
    public var metadata: [MediaObjectMetadataDescriptor]?
    public var uri: String?

    public init(object: MediaObjectDescriptor? = nil, metadata: [MediaObjectMetadataDescriptor]? = nil, uri: String? = nil) {
        self.object = object
        self.metadata = metadata
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case object
        case metadata
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(object, forKey: .object)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(uri, forKey: .uri)
    }
}

