//
// FeaturesByCategoryQueryResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FeaturesByCategoryQueryResult: Codable, JSONEncodable, Hashable {

    public var queryId: String?
    public var featureMap: [String: [[String: AnyCodable]]]?
    public var category: String?

    public init(queryId: String? = nil, featureMap: [String: [[String: AnyCodable]]]? = nil, category: String? = nil) {
        self.queryId = queryId
        self.featureMap = featureMap
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryId
        case featureMap
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(queryId, forKey: .queryId)
        try container.encodeIfPresent(featureMap, forKey: .featureMap)
        try container.encodeIfPresent(category, forKey: .category)
    }
}

