//
// FeaturesTextCategoryQueryResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FeaturesTextCategoryQueryResult: Codable, JSONEncodable, Hashable {

    public var queryId: String?
    public var featureValues: [String]?
    public var category: String?
    public var elementID: String?

    public init(queryId: String? = nil, featureValues: [String]? = nil, category: String? = nil, elementID: String? = nil) {
        self.queryId = queryId
        self.featureValues = featureValues
        self.category = category
        self.elementID = elementID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryId
        case featureValues
        case category
        case elementID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(queryId, forKey: .queryId)
        try container.encodeIfPresent(featureValues, forKey: .featureValues)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(elementID, forKey: .elementID)
    }
}

