//
// MediaObjectMetadataDescriptor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaObjectMetadataDescriptor: Codable, JSONEncodable, Hashable {

    public var objectid: String?
    public var domain: String?
    public var key: String?
    public var value: String?
    public var exists: Bool?

    public init(objectid: String? = nil, domain: String? = nil, key: String? = nil, value: String? = nil, exists: Bool? = nil) {
        self.objectid = objectid
        self.domain = domain
        self.key = key
        self.value = value
        self.exists = exists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objectid
        case domain
        case key
        case value
        case exists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(objectid, forKey: .objectid)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(exists, forKey: .exists)
    }
}

