//
// OptionallyFilteredIdList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OptionallyFilteredIdList: Codable, JSONEncodable, Hashable {

    public var filters: [AbstractMetadataFilterDescriptor]?
    public var ids: [String]

    public init(ids: [String]) {
        self.filters = nil
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filters, forKey: .filters)
        try container.encode(ids, forKey: .ids)
    }
}

