//
// SelectSpecification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SelectSpecification: Codable, JSONEncodable, Hashable {

    public var table: String
    public var columns: [String]
    public var limit: Int

    public init(table: String, columns: [String], limit: Int) {
        self.table = table
        self.columns = columns
        self.limit = limit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case table
        case columns
        case limit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(table, forKey: .table)
        try container.encode(columns, forKey: .columns)
        try container.encode(limit, forKey: .limit)
    }
}

