//
// SimilarityQueryResultBatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SimilarityQueryResultBatch: Codable, JSONEncodable, Hashable {

    public var categories: [String]?
    public var results: [SimilarityQueryResult]?

    public init(categories: [String]? = nil, results: [SimilarityQueryResult]? = nil) {
        self.categories = categories
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categories, forKey: .categories)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

