//
// StagedSimilarityQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StagedSimilarityQuery: Codable, JSONEncodable, Hashable {

    public var stages: [QueryStage]?
    public var config: QueryConfig?

    public init(stages: [QueryStage]? = nil, config: QueryConfig? = nil) {
        self.stages = stages
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stages
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(stages, forKey: .stages)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

