//
// TagsQueryResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TagsQueryResult: Codable, JSONEncodable, Hashable {

    public var queryId: String?
    public var tags: [Tag]?

    public init(queryId: String? = nil, tags: [Tag]? = nil) {
        self.queryId = queryId
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryId
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(queryId, forKey: .queryId)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

